OpenJPEG: test_sparse_array.c File Reference
test_sparse_array.c File Reference
#include "opj_includes.h"
Functions
int main ()
Function Documentation
main()
int main ()
References OPJ_FALSE, opj_sparse_array_int32_create(), opj_sparse_array_int32_free(), opj_sparse_array_int32_read(), and opj_sparse_array_int32_write().